# name: Astronomer CI - Deploy code to Astro

# on:
#   push:
#     branches:
#       - main

# env:
#   ## Sets Deployment API key credentials as environment variables
#   ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy to Astro
#       uses: astronomer/deploy-action@v0.2
#       with:
#         deployment-id: clgld5gzn08368nwaarplb91e


name: Astronomer CI - Push to Prod

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: clgld5gzn08368nwaarplb91e

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: get branch name
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - name: Deploy to Prod
      shell: bash
      run: |
        # install the Astro CLI
        curl -sSL https://install.astronomer.io | sudo bash -s

        # Deploy new code to the prod deployment
        astro deploy $DEPLOYMENT_ID -f